QT       += core gui
QT       += multimediawidgets
QT       += multimedia

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++17

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    src/app/game_app.cpp \
    src/common/map_transform.cpp \
    src/common/random.cpp \
    src/common/time_manager.cpp\
    src/main.cpp \
    src/model/level/level_manager.cpp \
    src/view/GUI_manager.cpp \
    src/viewmodel/card/card.cpp \
    src/viewmodel/card/cherry_card.cpp \
    src/viewmodel/card/egg_card.cpp \
    src/viewmodel/card/fish_card.cpp \
    src/viewmodel/card/hotpot_card.cpp \
    src/viewmodel/card/small_bread_card.cpp \
    src/viewmodel/card/steamdrawer_card.cpp \
    src/viewmodel/card/stove_card.cpp \
    src/viewmodel/card/super_egg_card.cpp \
    src/viewmodel/pool_manager.cpp \
    src/viewmodel/sprite/flame/flame.cpp \
    src/viewmodel/sprite/flame/flame_manager.cpp \
    src/viewmodel/sprite/food/cherry.cpp \
    src/viewmodel/sprite/food/egg.cpp \
    src/viewmodel/sprite/food/fish.cpp \
    src/viewmodel/sprite/food/food.cpp \
    src/viewmodel/sprite/food/food_manager.cpp \
    src/viewmodel/sprite/food/small_bread.cpp \
    src/viewmodel/sprite/food/steam_drawer.cpp \
    src/viewmodel/sprite/food/stove.cpp \
    src/viewmodel/sprite/food/super_egg.cpp \
    src/viewmodel/sprite/mouse/bucket_mouse.cpp \
    src/viewmodel/sprite/mouse/football_mouse.cpp \
    src/viewmodel/sprite/mouse/mouse.cpp \
    src/viewmodel/sprite/mouse/mouse_manager.cpp \
    src/viewmodel/sprite/mouse/normal_mouse.cpp \
    src/viewmodel/sprite/projectile/horizontal_projectile.cpp \
    src/viewmodel/sprite/projectile/pitch_projectile.cpp \
    src/viewmodel/sprite/projectile/projectile.cpp \
    src/viewmodel/sprite/projectile/projectile_manager.cpp \
    src/viewmodel/sprite/sprite.cpp

HEADERS += \
    src/app/game_app.h \
    src/common/debug.h \
    src/common/sprite_item.h \
    src/common/enums.h \
    src/common/map_transform.h \
    src/common/random.h \
    src/common/time_manager.h\
    src/model/level/level_manager.h \
    src/view/GUI_manager.h \
    src/viewmodel/card/card.h \
    src/viewmodel/card/cherry_card.h \
    src/viewmodel/card/egg_card.h \
    src/viewmodel/card/fish_card.h \
    src/viewmodel/card/hotpot_card.h \
    src/viewmodel/card/small_bread_card.h \
    src/viewmodel/card/steamdrawer_card.h \
    src/viewmodel/card/stove_card.h \
    src/viewmodel/card/super_egg_card.h \
    src/viewmodel/pool_manager.h \
    src/viewmodel/sprite/flame/flame.h \
    src/viewmodel/sprite/flame/flame_manager.h \
    src/viewmodel/sprite/food/cherry.h \
    src/viewmodel/sprite/food/egg.h \
    src/viewmodel/sprite/food/fish.h \
    src/viewmodel/sprite/food/food.h \
    src/viewmodel/sprite/food/food_manager.h \
    src/viewmodel/sprite/food/small_bread.h \
    src/viewmodel/sprite/food/steam_drawer.h \
    src/viewmodel/sprite/food/stove.h \
    src/viewmodel/sprite/food/super_egg.h \
    src/viewmodel/sprite/mouse/bucket_mouse.h \
    src/viewmodel/sprite/mouse/football_mouse.h \
    src/viewmodel/sprite/mouse/mouse.h \
    src/viewmodel/sprite/mouse/mouse_manager.h \
    src/viewmodel/sprite/mouse/normal_mouse.h \
    src/viewmodel/sprite/projectile/horizontal_projectile.h \
    src/viewmodel/sprite/projectile/pitch_projectile.h \
    src/viewmodel/sprite/projectile/projectile.h \
    src/viewmodel/sprite/projectile/projectile_manager.h \
    src/viewmodel/sprite/sprite.h

FORMS += 

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

DISTFILES += \
    resources/convert/Video/0x111E0020_2022-06-30-08-25-11.aac \
    resources/convert/image/0x111E0020_2022-06-30-08-27-43/image001.png \
    resources/convert/image/0x111E0020_2022-06-30-08-27-43/image002.png \
    resources/convert/image/0x111E0020_2022-06-30-08-27-43/image003.png \
    resources/convert/image/0x111E0020_2022-06-30-08-27-43/image004.png \
    resources/convert/image/0x111E0020_2022-06-30-08-27-43/image005.png \
    resources/convert/image/0x111E0020_2022-06-30-08-27-43/image006.png \
    resources/convert/image/0x111E0020_2022-06-30-08-27-43/image007.png \
    resources/convert/image/0x111E0020_2022-06-30-08-27-43/image008.png \
    resources/convert/image/0x111E0020_2022-06-30-08-27-43/image009.png \
    resources/convert/image/0x111E0020_2022-06-30-08-27-43/image010.png \
    resources/convert/image/0x111E0020_2022-06-30-08-27-43/image011.png \
    resources/convert/image/0x111E0020_2022-06-30-08-27-43/image012.png \
    resources/convert/image/0x111E0020_2022-06-30-08-27-43/image013.png \
    resources/convert/image/0x111E0020_2022-06-30-08-27-43/image014.png \
    resources/levels/first.txt \
    resources/music/Cerebrawl.mp3 \
    resources/music/Loonboon.mp3 \
    resources/music/chomp.mp3 \
    resources/music/dirt_rise.mp3 \
    resources/music/gravebusterchomp.mp3 \
    resources/music/groan.mp3 \
    resources/music/groan2.mp3 \
    resources/music/groan3.mp3 \
    resources/music/groan4.mp3 \
    resources/music/groan5.mp3 \
    resources/music/groan6.mp3 \
    resources/music/hit.mp3 \
    resources/music/lawnmower.mp3 \
    resources/music/losemusic.mp3 \
    resources/music/plant.mp3 \
    resources/music/potato_mine.mp3 \
    resources/music/shoop.mp3 \
    resources/music/sunshine.mp3 \
    resources/music/theZombiesareComing.mp3 \
    resources/music/trophy.mp3 \
    resources/picture/Bullet/1 1.png \
    resources/picture/Bullet/1.png \
    resources/picture/Bullet/2.png \
    resources/picture/Bullet/3.png \
    resources/picture/Bullet/4.png \
    resources/picture/Bullet/5.png \
    resources/picture/GraveStones/1.png \
    resources/picture/GraveStones/2.png \
    resources/picture/GraveStones/3.png \
    resources/picture/GraveStones/4.png \
    resources/picture/GraveStones/5.png \
    resources/picture/GraveStones/6.png \
    resources/picture/GraveStones/7.png \
    resources/picture/GraveStones/8.png \
    resources/picture/Plants/GraveBuster/GraveBuster-1.png \
    resources/picture/Plants/GraveBuster/GraveBuster-10.png \
    resources/picture/Plants/GraveBuster/GraveBuster-11.png \
    resources/picture/Plants/GraveBuster/GraveBuster-12.png \
    resources/picture/Plants/GraveBuster/GraveBuster-13.png \
    resources/picture/Plants/GraveBuster/GraveBuster-14.png \
    resources/picture/Plants/GraveBuster/GraveBuster-15.png \
    resources/picture/Plants/GraveBuster/GraveBuster-16.png \
    resources/picture/Plants/GraveBuster/GraveBuster-17.png \
    resources/picture/Plants/GraveBuster/GraveBuster-18.png \
    resources/picture/Plants/GraveBuster/GraveBuster-19.png \
    resources/picture/Plants/GraveBuster/GraveBuster-2.png \
    resources/picture/Plants/GraveBuster/GraveBuster-20.png \
    resources/picture/Plants/GraveBuster/GraveBuster-21.png \
    resources/picture/Plants/GraveBuster/GraveBuster-22.png \
    resources/picture/Plants/GraveBuster/GraveBuster-23.png \
    resources/picture/Plants/GraveBuster/GraveBuster-24.png \
    resources/picture/Plants/GraveBuster/GraveBuster-25.png \
    resources/picture/Plants/GraveBuster/GraveBuster-26.png \
    resources/picture/Plants/GraveBuster/GraveBuster-27.png \
    resources/picture/Plants/GraveBuster/GraveBuster-28.png \
    resources/picture/Plants/GraveBuster/GraveBuster-3.png \
    resources/picture/Plants/GraveBuster/GraveBuster-4.png \
    resources/picture/Plants/GraveBuster/GraveBuster-5.png \
    resources/picture/Plants/GraveBuster/GraveBuster-6.png \
    resources/picture/Plants/GraveBuster/GraveBuster-7.png \
    resources/picture/Plants/GraveBuster/GraveBuster-8.png \
    resources/picture/Plants/GraveBuster/GraveBuster-9.png \
    resources/picture/Plants/IceShroom/IceShroom/IceShroom_0.png \
    resources/picture/Plants/IceShroom/IceShroom/IceShroom_1.png \
    resources/picture/Plants/IceShroom/IceShroom/IceShroom_10.png \
    resources/picture/Plants/IceShroom/IceShroom/IceShroom_2.png \
    resources/picture/Plants/IceShroom/IceShroom/IceShroom_3.png \
    resources/picture/Plants/IceShroom/IceShroom/IceShroom_4.png \
    resources/picture/Plants/IceShroom/IceShroom/IceShroom_5.png \
    resources/picture/Plants/IceShroom/IceShroom/IceShroom_6.png \
    resources/picture/Plants/IceShroom/IceShroom/IceShroom_7.png \
    resources/picture/Plants/IceShroom/IceShroom/IceShroom_8.png \
    resources/picture/Plants/IceShroom/IceShroom/IceShroom_9.png \
    resources/picture/Plants/IceShroom/IceShroomSnow_0.png \
    resources/picture/Plants/IceShroom/IceShroomTrap_0.png \
    resources/picture/Plants/PotatoMine/PotatoMine/PotatoMine_0.png \
    resources/picture/Plants/PotatoMine/PotatoMine/PotatoMine_1.png \
    resources/picture/Plants/PotatoMine/PotatoMine/PotatoMine_2.png \
    resources/picture/Plants/PotatoMine/PotatoMine/PotatoMine_3.png \
    resources/picture/Plants/PotatoMine/PotatoMine/PotatoMine_4.png \
    resources/picture/Plants/PotatoMine/PotatoMine/PotatoMine_5.png \
    resources/picture/Plants/PotatoMine/PotatoMine/PotatoMine_6.png \
    resources/picture/Plants/PotatoMine/PotatoMine/PotatoMine_7.png \
    resources/picture/Plants/PotatoMine/PotatoMineExplode/PotatoMineExplode_0.png \
    resources/picture/Plants/PotatoMine/PotatoMineInit/PotatoMineInit_0.png \
    resources/picture/Plants/Sun/Sun_0.png \
    resources/picture/Plants/Sun/Sun_1.png \
    resources/picture/Plants/Sun/Sun_10.png \
    resources/picture/Plants/Sun/Sun_11.png \
    resources/picture/Plants/Sun/Sun_12.png \
    resources/picture/Plants/Sun/Sun_13.png \
    resources/picture/Plants/Sun/Sun_14.png \
    resources/picture/Plants/Sun/Sun_15.png \
    resources/picture/Plants/Sun/Sun_16.png \
    resources/picture/Plants/Sun/Sun_17.png \
    resources/picture/Plants/Sun/Sun_18.png \
    resources/picture/Plants/Sun/Sun_19.png \
    resources/picture/Plants/Sun/Sun_2.png \
    resources/picture/Plants/Sun/Sun_20.png \
    resources/picture/Plants/Sun/Sun_21.png \
    resources/picture/Plants/Sun/Sun_3.png \
    resources/picture/Plants/Sun/Sun_4.png \
    resources/picture/Plants/Sun/Sun_5.png \
    resources/picture/Plants/Sun/Sun_6.png \
    resources/picture/Plants/Sun/Sun_7.png \
    resources/picture/Plants/Sun/Sun_8.png \
    resources/picture/Plants/Sun/Sun_9.png \
    resources/picture/Screen/1.png \
    resources/picture/Screen/2.png \
    resources/picture/Screen/3.png \
    resources/picture/Screen/Background.jpg \
    resources/picture/Screen/ChooserBackground.png \
    resources/picture/Screen/background_game1.png \
    resources/picture/Screen/bang.png \
    resources/picture/Screen/hammer/hammer1.png \
    resources/picture/Screen/hammer/hammer10.png \
    resources/picture/Screen/hammer/hammer11.png \
    resources/picture/Screen/hammer/hammer12.png \
    resources/picture/Screen/hammer/hammer13.png \
    resources/picture/Screen/hammer/hammer2.png \
    resources/picture/Screen/hammer/hammer3.png \
    resources/picture/Screen/hammer/hammer4.png \
    resources/picture/Screen/hammer/hammer5.png \
    resources/picture/Screen/hammer/hammer6.png \
    resources/picture/Screen/hammer/hammer7.png \
    resources/picture/Screen/hammer/hammer8.png \
    resources/picture/Screen/hammer/hammer9.png \
    resources/picture/Screen/lawnmower.png \
    resources/picture/Screen/lose.png \
    resources/picture/Screen/menu.png \
    resources/picture/Screen/selectID.png \
    resources/picture/Screen/win.png \
    resources/picture/SteamedBun/1.png \
    resources/picture/SteamedBun/10.png \
    resources/picture/SteamedBun/11.png \
    resources/picture/SteamedBun/12.png \
    resources/picture/SteamedBun/13.png \
    resources/picture/SteamedBun/14.png \
    resources/picture/SteamedBun/15.png \
    resources/picture/SteamedBun/16.png \
    resources/picture/SteamedBun/17.png \
    resources/picture/SteamedBun/18.png \
    resources/picture/SteamedBun/2.png \
    resources/picture/SteamedBun/3.png \
    resources/picture/SteamedBun/4.png \
    resources/picture/SteamedBun/5.png \
    resources/picture/SteamedBun/6.png \
    resources/picture/SteamedBun/7.png \
    resources/picture/SteamedBun/8.png \
    resources/picture/SteamedBun/9.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-1.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-10.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-11.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-12.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-13.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-14.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-15.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-16.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-17.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-18.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-19.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-2.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-20.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-21.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-22.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-23.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-24.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-25.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-26.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-27.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-28.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-29.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-3.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-30.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-31.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-32.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-33.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-34.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-35.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-36.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-37.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-38.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-39.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-4.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-40.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-41.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-42.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-43.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-44.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-45.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-46.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-47.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-5.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-6.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-7.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-8.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombie/BucketheadZombie-9.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieAttack/BucketheadZombieAttack_0.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieAttack/BucketheadZombieAttack_1.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieAttack/BucketheadZombieAttack_10.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieAttack/BucketheadZombieAttack_2.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieAttack/BucketheadZombieAttack_3.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieAttack/BucketheadZombieAttack_4.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieAttack/BucketheadZombieAttack_5.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieAttack/BucketheadZombieAttack_6.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieAttack/BucketheadZombieAttack_7.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieAttack/BucketheadZombieAttack_8.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieAttack/BucketheadZombieAttack_9.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieEmerge/Zombie-1.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieEmerge/Zombie-10.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieEmerge/Zombie-11.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieEmerge/Zombie-12.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieEmerge/Zombie-13.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieEmerge/Zombie-14.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieEmerge/Zombie-15.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieEmerge/Zombie-16.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieEmerge/Zombie-17.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieEmerge/Zombie-18.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieEmerge/Zombie-19.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieEmerge/Zombie-2.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieEmerge/Zombie-20.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieEmerge/Zombie-3.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieEmerge/Zombie-4.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieEmerge/Zombie-5.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieEmerge/Zombie-6.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieEmerge/Zombie-7.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieEmerge/Zombie-8.png \
    resources/picture/Zombies/BucketheadZombie/BucketheadZombieEmerge/Zombie-9.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-1.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-10.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-11.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-12.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-13.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-14.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-15.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-16.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-17.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-18.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-19.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-2.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-20.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-21.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-22.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-23.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-24.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-25.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-26.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-27.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-28.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-29.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-3.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-30.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-31.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-32.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-33.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-34.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-35.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-36.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-37.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-38.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-39.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-4.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-40.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-41.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-42.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-43.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-44.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-45.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-46.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-47.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-5.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-6.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-7.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-8.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombie/ConeheadZombie-9.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieAttack/ConeheadZombieAttack_0.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieAttack/ConeheadZombieAttack_1.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieAttack/ConeheadZombieAttack_10.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieAttack/ConeheadZombieAttack_2.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieAttack/ConeheadZombieAttack_3.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieAttack/ConeheadZombieAttack_4.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieAttack/ConeheadZombieAttack_5.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieAttack/ConeheadZombieAttack_6.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieAttack/ConeheadZombieAttack_7.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieAttack/ConeheadZombieAttack_8.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieAttack/ConeheadZombieAttack_9.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieEmerge/Zombie-1.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieEmerge/Zombie-10.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieEmerge/Zombie-11.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieEmerge/Zombie-12.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieEmerge/Zombie-13.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieEmerge/Zombie-14.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieEmerge/Zombie-15.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieEmerge/Zombie-16.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieEmerge/Zombie-17.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieEmerge/Zombie-18.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieEmerge/Zombie-19.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieEmerge/Zombie-2.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieEmerge/Zombie-20.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieEmerge/Zombie-3.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieEmerge/Zombie-4.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieEmerge/Zombie-5.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieEmerge/Zombie-6.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieEmerge/Zombie-7.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieEmerge/Zombie-8.png \
    resources/picture/Zombies/ConeheadZombie/ConeheadZombieEmerge/Zombie-9.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-1.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-10.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-11.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-12.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-13.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-14.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-15.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-16.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-17.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-18.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-19.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-2.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-20.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-21.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-22.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-23.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-24.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-25.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-26.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-27.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-28.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-29.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-3.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-30.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-31.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-32.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-33.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-34.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-35.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-36.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-37.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-38.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-39.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-4.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-40.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-41.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-42.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-43.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-44.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-45.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-46.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-47.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-5.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-6.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-7.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-8.png \
    resources/picture/Zombies/NormalZombie/Zombie/Zombie-9.png \
    resources/picture/Zombies/NormalZombie/ZombieAttack/ZombieAttack_0.png \
    resources/picture/Zombies/NormalZombie/ZombieAttack/ZombieAttack_1.png \
    resources/picture/Zombies/NormalZombie/ZombieAttack/ZombieAttack_10.png \
    resources/picture/Zombies/NormalZombie/ZombieAttack/ZombieAttack_2.png \
    resources/picture/Zombies/NormalZombie/ZombieAttack/ZombieAttack_3.png \
    resources/picture/Zombies/NormalZombie/ZombieAttack/ZombieAttack_4.png \
    resources/picture/Zombies/NormalZombie/ZombieAttack/ZombieAttack_5.png \
    resources/picture/Zombies/NormalZombie/ZombieAttack/ZombieAttack_6.png \
    resources/picture/Zombies/NormalZombie/ZombieAttack/ZombieAttack_7.png \
    resources/picture/Zombies/NormalZombie/ZombieAttack/ZombieAttack_8.png \
    resources/picture/Zombies/NormalZombie/ZombieAttack/ZombieAttack_9.png \
    resources/picture/Zombies/NormalZombie/ZombieEmerge/Zombie-1.png \
    resources/picture/Zombies/NormalZombie/ZombieEmerge/Zombie-10.png \
    resources/picture/Zombies/NormalZombie/ZombieEmerge/Zombie-11.png \
    resources/picture/Zombies/NormalZombie/ZombieEmerge/Zombie-12.png \
    resources/picture/Zombies/NormalZombie/ZombieEmerge/Zombie-13.png \
    resources/picture/Zombies/NormalZombie/ZombieEmerge/Zombie-14.png \
    resources/picture/Zombies/NormalZombie/ZombieEmerge/Zombie-15.png \
    resources/picture/Zombies/NormalZombie/ZombieEmerge/Zombie-16.png \
    resources/picture/Zombies/NormalZombie/ZombieEmerge/Zombie-17.png \
    resources/picture/Zombies/NormalZombie/ZombieEmerge/Zombie-18.png \
    resources/picture/Zombies/NormalZombie/ZombieEmerge/Zombie-19.png \
    resources/picture/Zombies/NormalZombie/ZombieEmerge/Zombie-2.png \
    resources/picture/Zombies/NormalZombie/ZombieEmerge/Zombie-20.png \
    resources/picture/Zombies/NormalZombie/ZombieEmerge/Zombie-3.png \
    resources/picture/Zombies/NormalZombie/ZombieEmerge/Zombie-4.png \
    resources/picture/Zombies/NormalZombie/ZombieEmerge/Zombie-5.png \
    resources/picture/Zombies/NormalZombie/ZombieEmerge/Zombie-6.png \
    resources/picture/Zombies/NormalZombie/ZombieEmerge/Zombie-7.png \
    resources/picture/Zombies/NormalZombie/ZombieEmerge/Zombie-8.png \
    resources/picture/Zombies/NormalZombie/ZombieEmerge/Zombie-9.png \
    resources/picture/flame/1.png \
    resources/picture/flame/10.png \
    resources/picture/flame/2.png \
    resources/picture/flame/3.png \
    resources/picture/flame/4.png \
    resources/picture/flame/5.png \
    resources/picture/flame/6.png \
    resources/picture/flame/7.png \
    resources/picture/flame/8.png \
    resources/picture/flame/9.png \
    resources/picture/food/Cherrys_tart/Cherry_b/1.png \
    resources/picture/food/Cherrys_tart/Cherry_boom/2.png \
    resources/picture/food/Cherrys_tart/Cherry_boom/3.png \
    resources/picture/food/Cherrys_tart/Cherry_boom/4.png \
    resources/picture/food/Cherrys_tart/Cherry_boom/5.png \
    resources/picture/food/Cherrys_tart/Cherry_tart/1.png \
    resources/picture/food/Cherrys_tart/Cherry_tart/2.png \
    resources/picture/food/Cherrys_tart/Cherry_tart/3.png \
    resources/picture/food/Cherrys_tart/Cherry_tart/4.png \
    resources/picture/food/Cherrys_tart/Cherry_tart/5.png \
    resources/picture/food/Cherrys_tart/Cherry_tart/6.png \
    resources/picture/food/Cherrys_tart/Cherry_tart/7.png \
    resources/picture/food/Cherrys_tart/Cherry_tart/8.png \
    resources/picture/food/Cherrys_tart/Cherry_tart/9.png \
    resources/picture/food/Eggs_pitcher/Egg_boom/boom_1.png \
    resources/picture/food/Eggs_pitcher/Egg_boom/boom_2.png \
    resources/picture/food/Eggs_pitcher/Egg_boom/boom_3.png \
    resources/picture/food/Eggs_pitcher/Egg_boom/boom_4.png \
    resources/picture/food/Eggs_pitcher/Egg_boom/boom_5.png \
    resources/picture/food/Eggs_pitcher/Egg_boom/boom_6.png \
    resources/picture/food/Eggs_pitcher/Egg_pitcher/1.png \
    resources/picture/food/Eggs_pitcher/Egg_pitcher/10.png \
    resources/picture/food/Eggs_pitcher/Egg_pitcher/11.png \
    resources/picture/food/Eggs_pitcher/Egg_pitcher/12.png \
    resources/picture/food/Eggs_pitcher/Egg_pitcher/13.png \
    resources/picture/food/Eggs_pitcher/Egg_pitcher/14.png \
    resources/picture/food/Eggs_pitcher/Egg_pitcher/15.png \
    resources/picture/food/Eggs_pitcher/Egg_pitcher/16.png \
    resources/picture/food/Eggs_pitcher/Egg_pitcher/17.png \
    resources/picture/food/Eggs_pitcher/Egg_pitcher/18.png \
    resources/picture/food/Eggs_pitcher/Egg_pitcher/19.png \
    resources/picture/food/Eggs_pitcher/Egg_pitcher/2.png \
    resources/picture/food/Eggs_pitcher/Egg_pitcher/20.png \
    resources/picture/food/Eggs_pitcher/Egg_pitcher/21.png \
    resources/picture/food/Eggs_pitcher/Egg_pitcher/22.png \
    resources/picture/food/Eggs_pitcher/Egg_pitcher/23.png \
    resources/picture/food/Eggs_pitcher/Egg_pitcher/24.png \
    resources/picture/food/Eggs_pitcher/Egg_pitcher/25.png \
    resources/picture/food/Eggs_pitcher/Egg_pitcher/26.png \
    resources/picture/food/Eggs_pitcher/Egg_pitcher/3.png \
    resources/picture/food/Eggs_pitcher/Egg_pitcher/4.png \
    resources/picture/food/Eggs_pitcher/Egg_pitcher/5.png \
    resources/picture/food/Eggs_pitcher/Egg_pitcher/6.png \
    resources/picture/food/Eggs_pitcher/Egg_pitcher/7.png \
    resources/picture/food/Eggs_pitcher/Egg_pitcher/8.png \
    resources/picture/food/Eggs_pitcher/Egg_pitcher/9.png \
    resources/picture/food/Eggs_pitcher/Eggs/Egg_1.png \
    resources/picture/food/Eggs_pitcher/Eggs/Egg_2.png \
    resources/picture/food/Eggs_pitcher/Eggs/Egg_3.png \
    resources/picture/food/Eggs_pitcher/Eggs/Egg_4.png \
    resources/picture/food/Eggs_pitcher/Eggs/Egg_5.png \
    resources/picture/food/Hots_pot/Hotpot/1.png \
    resources/picture/food/Hots_pot/Hotpot/10.png \
    resources/picture/food/Hots_pot/Hotpot/11.png \
    resources/picture/food/Hots_pot/Hotpot/12.png \
    resources/picture/food/Hots_pot/Hotpot/13.png \
    resources/picture/food/Hots_pot/Hotpot/2.png \
    resources/picture/food/Hots_pot/Hotpot/3.png \
    resources/picture/food/Hots_pot/Hotpot/4.png \
    resources/picture/food/Hots_pot/Hotpot/5.png \
    resources/picture/food/Hots_pot/Hotpot/6.png \
    resources/picture/food/Hots_pot/Hotpot/7.png \
    resources/picture/food/Hots_pot/Hotpot/8.png \
    resources/picture/food/Hots_pot/Hotpot/9.png \
    resources/picture/food/Hots_pot/Hotpot_b/14.png \
    resources/picture/food/Hots_pot/Hotpot_b/15.png \
    resources/picture/food/Hots_pot/Hotpot_b/16.png \
    resources/picture/food/Hots_pot/Hotpot_b/17.png \
    resources/picture/food/Hots_pot/Hotpot_b/18.png \
    resources/picture/food/Hots_pot/Hotpot_b/19.png \
    resources/picture/food/Hots_pot/Hotpot_b/20.png \
    resources/picture/food/Hots_pot/Hotpot_b/21.png \
    resources/picture/food/Hots_pot/Hotpot_b/22.png \
    resources/picture/food/Hots_pot/Hotpot_b/23.png \
    resources/picture/food/Hots_pot/Hotpot_b/24.png \
    resources/picture/food/Hots_pot/Hotpot_b/25.png \
    resources/picture/food/Hots_pot/Hotpot_b/26.png \
    resources/picture/food/Hots_pot/Hotpot_b/27.png \
    resources/picture/food/Hots_pot/Hotpot_b/28.png \
    resources/picture/food/Hots_pot/Hotpot_b/29.png \
    resources/picture/food/Hots_pot/Hotpot_b/30.png \
    resources/picture/food/Hots_pot/Hotpot_b/31.png \
    resources/picture/food/Hots_pot/Hotpot_b/32.png \
    resources/picture/food/Hots_pot/Hotpot_b/33.png \
    resources/picture/food/Hots_pot/Hotpot_b/34.png \
    resources/picture/food/Hots_pot/Hotpot_b/35.png \
    resources/picture/food/Hots_pot/Hotpot_b/36.png \
    resources/picture/food/Hots_pot/Hotpot_b/37.png \
    resources/picture/food/Hots_pot/Hotpot_b/38.png \
    resources/picture/food/Hots_pot/Hotpot_b/39.png \
    resources/picture/food/Hots_pot/Hotpot_b/40.png \
    resources/picture/food/Hots_pot/Hotpot_b/41.png \
    resources/picture/food/Hots_pot/Hotpot_b/42.png \
    resources/picture/food/Hots_pot/Hotpot_b/43.png \
    resources/picture/food/Hots_pot/Hotpot_b/44.png \
    resources/picture/food/Hots_pot/Hotpot_b/45.png \
    resources/picture/food/Hots_pot/Hotpot_b/46.png \
    resources/picture/food/Hots_pot/Hotpot_b/47.png \
    resources/picture/food/Hots_pot/Hotpot_b/48.png \
    resources/picture/food/Hots_pot/Hotpot_b/49.png \
    resources/picture/food/Hots_pot/Hotpot_b/50.png \
    resources/picture/food/Hots_pot/Hotpot_b/51.png \
    resources/picture/food/Hots_pot/Hotpot_b/52.png \
    resources/picture/food/Hots_pot/Hotpot_b/53.png \
    resources/picture/food/Hots_pot/Hotpot_b/54.png \
    resources/picture/food/Hots_pot/Hotpot_b/55.png \
    resources/picture/mouse/Jump_mouse/Jump_1.png \
    resources/picture/mouse/Jump_mouse/Jump_2.png \
    resources/picture/mouse/Jump_mouse/Jump_3.png \
    resources/picture/mouse/Jump_mouse/Jump_4.png \
    resources/picture/mouse/Jump_mouse/Jump_5.png \
    resources/picture/mouse/Jump_mouse/Jump_6.png \
    resources/picture/mouse/Jump_mouse/Jump_7.png \
    resources/picture/mouse/Jump_mouse/Jump_8.png \
    resources/picture/mouse/Ninja_mouse/Ninja_1.png \
    resources/picture/mouse/Ninja_mouse/Ninja_2.png \
    resources/picture/mouse/Ninja_mouse/Ninja_3.png \
    resources/picture/mouse/Ninja_mouse/Ninja_4.png \
    resources/picture/mouse/Ninja_mouse/Ninja_5.png \
    resources/picture/mouse/Ninja_mouse/Ninja_6.png \
    resources/picture/mouse/Sun_mouse/1.png \
    resources/picture/mouse/Sun_mouse/10.png \
    resources/picture/mouse/Sun_mouse/11.png \
    resources/picture/mouse/Sun_mouse/12.png \
    resources/picture/mouse/Sun_mouse/2.png \
    resources/picture/mouse/Sun_mouse/3.png \
    resources/picture/mouse/Sun_mouse/4.png \
    resources/picture/mouse/Sun_mouse/5.png \
    resources/picture/mouse/Sun_mouse/6.png \
    resources/picture/mouse/Sun_mouse/7.png \
    resources/picture/mouse/Sun_mouse/8.png \
    resources/picture/mouse/Sun_mouse/9.png \
    resources/picture/mouse/normal_mouse/normal_die/die_1.png \
    resources/picture/mouse/normal_mouse/normal_die/die_10.png \
    resources/picture/mouse/normal_mouse/normal_die/die_11.png \
    resources/picture/mouse/normal_mouse/normal_die/die_12.png \
    resources/picture/mouse/normal_mouse/normal_die/die_13.png \
    resources/picture/mouse/normal_mouse/normal_die/die_2.png \
    resources/picture/mouse/normal_mouse/normal_die/die_3.png \
    resources/picture/mouse/normal_mouse/normal_die/die_4.png \
    resources/picture/mouse/normal_mouse/normal_die/die_5.png \
    resources/picture/mouse/normal_mouse/normal_die/die_6.png \
    resources/picture/mouse/normal_mouse/normal_die/die_7.png \
    resources/picture/mouse/normal_mouse/normal_die/die_8.png \
    resources/picture/mouse/normal_mouse/normal_die/die_9.png \
    resources/picture/mouse/normal_mouse/normal_eat1/eat1_1.png \
    resources/picture/mouse/normal_mouse/normal_eat1/eat1_2.png \
    resources/picture/mouse/normal_mouse/normal_eat1/eat1_3.png \
    resources/picture/mouse/normal_mouse/normal_eat1/eat1_4.png \
    resources/picture/mouse/normal_mouse/normal_eat2/eat2_1.png \
    resources/picture/mouse/normal_mouse/normal_eat2/eat2_2.png \
    resources/picture/mouse/normal_mouse/normal_eat2/eat2_3.png \
    resources/picture/mouse/normal_mouse/normal_eat2/eat2_4.png \
    resources/picture/mouse/normal_mouse/normal_walk1/walk1_1.png \
    resources/picture/mouse/normal_mouse/normal_walk1/walk1_2.png \
    resources/picture/mouse/normal_mouse/normal_walk1/walk1_3.png \
    resources/picture/mouse/normal_mouse/normal_walk1/walk1_4.png \
    resources/picture/mouse/normal_mouse/normal_walk1/walk1_5.png \
    resources/picture/mouse/normal_mouse/normal_walk1/walk1_6.png \
    resources/picture/mouse/normal_mouse/normal_walk1/walk1_7.png \
    resources/picture/mouse/normal_mouse/normal_walk1/walk1_8.png \
    resources/picture/mouse/normal_mouse/normal_walk2/walk2_1.png \
    resources/picture/mouse/normal_mouse/normal_walk2/walk2_2.png \
    resources/picture/mouse/normal_mouse/normal_walk2/walk2_3.png \
    resources/picture/mouse/normal_mouse/normal_walk2/walk2_4.png \
    resources/picture/mouse/normal_mouse/normal_walk2/walk2_5.png \
    resources/picture/mouse/normal_mouse/normal_walk2/walk2_6.png \
    resources/picture/mouse/normal_mouse/normal_walk2/walk2_7.png \
    resources/picture/mouse/normal_mouse/normal_walk2/walk2_8.png \
    resources/picture/stove/1.png \
    resources/picture/stove/10.png \
    resources/picture/stove/11.png \
    resources/picture/stove/12.png \
    resources/picture/stove/13.png \
    resources/picture/stove/14.png \
    resources/picture/stove/15.png \
    resources/picture/stove/16.png \
    resources/picture/stove/17.png \
    resources/picture/stove/18.png \
    resources/picture/stove/19.png \
    resources/picture/stove/2.png \
    resources/picture/stove/20.png \
    resources/picture/stove/21.png \
    resources/picture/stove/22.png \
    resources/picture/stove/23.png \
    resources/picture/stove/24.png \
    resources/picture/stove/25.png \
    resources/picture/stove/26.png \
    resources/picture/stove/27.png \
    resources/picture/stove/28.png \
    resources/picture/stove/29.png \
    resources/picture/stove/3.png \
    resources/picture/stove/4.png \
    resources/picture/stove/5.png \
    resources/picture/stove/6.png \
    resources/picture/stove/7.png \
    resources/picture/stove/8.png \
    resources/picture/stove/9.png

RESOURCES += \
    resources.qrc
